-- Run the command psql -f ./db/db_setup.sql (makes the database)
-- \c database_changes the current database to the specified one
-- use the \dt (or \dt+) command from the PostgreSQL command prompt to show tables in the chosen database
-- use the \d TABLE_name (or \d+ table_name) command to show details of a specific table
--  \conninfo displays information about current connection - tells what port is connected to

--DROP DATABASE IF EXISTS record_shop;
--CREATE DATABASE record_shop;

--\c record_shop;

--CREATE TYPE album_genre AS ENUM (
  --  'BLUES_GOSPEL',
    --'CLASSICAL',
   -- 'COUNTRY',
   -- 'DANCE_ELECTRONIC',
   -- 'EASY_LISTENING',
   -- 'FOLK_MUSIC',
   -- 'FUNK_SOUL',
   -- 'HIP_HOP',
    -- 'INDIE',
   -- 'JAZZ',
   -- 'K_POP',
   -- 'METAL',
   -- 'POP',
   -- 'PROG_ROCK',
    -- 'ROCK',
   -- 'REGGAE',
   -- 'SOUL',
    -- 'SOUNDTRACKS',
    -- 'SPOKEN_WORD_HUMOUR',
    -- 'WORLD_MUSIC'
--);

--CREATE TABLE albums
--(
  --  id SERIAL PRIMARY KEY,
  --  album_name VARCHAR,
  --  artist VARCHAR,
  --  copies_in_stock INT,
  --  genre album_genre NOT NULL,
  --  release_year INT
--);
